"""Run every demo input through the real pipeline (via the same service code as the web app,
on a fresh in-memory database) and write docs/DEMO_SCRIPT.md with the actual outputs.

    python scripts/run_demo_script.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from nagarvani import config, data, service  # noqa: E402
from nagarvani.console import safe_console  # noqa: E402
from nagarvani.examples import EXAMPLES  # noqa: E402
from nagarvani.tickets import Store  # noqa: E402

SAY = {
    "clean_marathi": "A clear complaint, a known place, high confidence: it goes straight to the department. R12 (water outage of two days or more) raises it to P2.",
    "romanised": "Romanised Marathi works because the classifier uses character n-grams and the gazetteer has Latin aliases.",
    "code_mixed": "Marathi and English mixed in one sentence, as people actually speak. Two hazard rules fire (nuisance and blocked drain).",
    "life_safety": "The rule base, not the model, decides life safety. R02 (open manhole) fires on the cue words shown and sets P1; R30 (near a school) fires too, but P1 is already the top band.",
    "fuzzy": "हडप्सर is not a gazetteer alias, but it is within the similarity threshold of हडपसर, so the fuzzy fallback resolves it and the trace shows the score.",
    "unknown_place": "Pimple Saudagar is in Pimpri-Chinchwad, not PMC, and is not in the gazetteer. The system does not guess a ward, so the gate sends it to a nodal officer. The citizen could also pick a ward in the optional dropdown.",
    "low_confidence": "Debris at the roadside could be Roads or Solid Waste. The top probability is under 0.50, so it defers instead of guessing, with the top three departments filled in for the officer.",
    "failure": "An honest failure, from the model's real errors on the test set: a drain that smells and breeds mosquitoes is read as Solid Waste. Its confidence is above 0.50 and the place is known, so the gate does NOT catch it. The officer corrects it, and the correction is logged.",
}



REJECTED_LOW_CONFIDENCE = ["कोथरूडमध्ये खूप त्रास होतोय, कोणीतरी लक्ष द्या", "कर्वेनगरमध्ये बांधकामाचे साहित्य रस्त्यावर ठेवले आहे"]
REJECTED_UNKNOWN_PLACE = ["उंड्री येथे रस्त्यावर मोठे खड्डे पडले आहेत", "लोहगाव मध्ये कचरा उचलला जात नाही"]
REJECTED_LIFE_SAFETY = ["धनकवडीत मॅनहोलचे झाकण गायब आहे, शाळकरी मुले रोज इथून जातात"]


def row(store, tid):
    t = store.get(tid)
    tr = json.loads(t["trace_json"])
    rules = ", ".join(f"{f['rule']} ({f['action']})" for f in tr["severity"]["fired"]) or "none (default P3)"
    top3 = ", ".join(f"{d} {p:.2f}" for d, p in tr["top3"])
    w = tr["ward"]
    ward = f"{w['ward']} ({data.ward_names()[w['ward']]['en']}) via {w['method']}" if w["ward"] else f"not resolved ({w['reason']})"
    if w["method"] == "fuzzy":
        ward += f", nearest alias '{w['matched_alias']}', similarity {w['score']}"
    d = tr["duplicate"]
    dup = d["decision"] + (f", score {d['score']:.2f} vs #{d['ticket_id']}" if d["ticket_id"] else f" ({d['reason']})")
    return [f"* Ticket #{tid}: **{tr['gate']['decision']}**, status `{t['status']}`",
            f"* Department top 3: {top3}",
            f"* Ward: {ward}",
            f"* Severity: **{tr['severity']['band']}**; rules fired: {rules}",
            f"* Duplicate check: {dup}",
            f"* Gate reason: {tr['gate']['reason']}"]


def main():
    safe_console()
    store = Store(":memory:")
    ex = {e["key"]: e for e in EXAMPLES}
    L = ["# Demo script", "",
         "Generated by `python scripts/run_demo_script.py`. Each input below was run through the real",
         "pipeline (the same `service.submit` → `triage()` code the web app uses, on a fresh database), and",
         "the output shown is what it produced. Run `python scripts/reset_demo.py` before the demo: the",
         "seeded tickets do not touch these inputs' duplicate blocks, but re-check item 8 after any seed change.",
         "Every input is also a one-click example on the intake page (the fallback if the microphone fails).", "",
         f"Classifier: the original char + word TF-IDF logistic regression (C = 10), loaded from results/model.pkl.", ""]
    n = 0
    for key in ["clean_marathi", "romanised", "code_mixed", "life_safety", "fuzzy", "unknown_place", "low_confidence"]:
        n += 1
        e = ex[key]
        tid, _ = service.submit(store, text=e["text"], channel="typed")
        L += [f"## {n}. {e['behaviour']}", "", f"Input: `{e['text']}`", ""] + row(store, tid) + ["", f"Say: {SAY[key]}", ""]
    n += 1
    L += [f"## {n}. Triple duplicate with escalation", "",
          "Submit the three reports one after another (three different wordings of the same pothole).", ""]
    ids = []
    for key in ["dup1", "dup2", "dup3"]:
        e = ex[key]
        tid, _ = service.submit(store, text=e["text"], channel="typed")
        ids.append(tid)
        L += [f"### {e['behaviour']}", "", f"Input: `{e['text']}`", ""] + row(store, tid) + [""]
    p = store.get(ids[0])
    L += [f"Result on the first ticket #{ids[0]}: {p['report_count']} reports, priority **{p['priority']}**, "
          f"escalation note: \"{p['escalation']}\".", "",
          "Say: the reports are merged, not duplicated in the queue. At the third report R32 fires and the open ticket "
          "moves up one band. Show the first report's ticket in the officer queue: it is marked '3 reports' and 'escalated'.", ""]
    n += 1
    e = ex["failure"]
    tid, _ = service.submit(store, text=e["text"], channel="typed")
    test = {r["id"]: r for r in data.load_test()}["T054"]
    L += [f"## {n}. {e['behaviour']}", "", f"Input: `{e['text']}` (test item T054; gold label {test['dept']})", ""]
    L += row(store, tid) + ["", f"Say: {SAY['failure']}", ""]
    L += ["## Spoken versions", "",
          "Read any of the inputs aloud with the Marathi toggle on. The transcript appears for checking before submission.",
          "Whisper's transcript will differ from the typed text, so the outcome may differ. That is real, and it is",
          "why the citizen checks the transcript. If the microphone fails, use the example buttons.",
          "A WhatsApp voice note (.ogg) can be uploaded with the file button.", ""]
    from nagarvani.triage import triage
    def tried(texts):
        out = []
        for t in texts:
            r = triage(t)
            out.append(f"  * `{t}` → {r.department} {r.confidence:.2f}, ward {r.ward.ward or 'none'}, "
                       f"{r.severity['band']}, {r.gate.decision}")
        return out
    L += ["## Inputs that were tried and rejected (re-run just now)", "",
          "* For item 7 (low confidence → review):", *tried(REJECTED_LOW_CONFIDENCE),
          "  The first shows a real weakness: a vague complaint is confidently sent to Health and auto-routed.",
          "* For item 6 (unknown locality): these places turned out to be in the gazetteer:", *tried(REJECTED_UNKNOWN_PLACE),
          "* For item 4 (life safety): 'झाकण गायब' (cover missing) does not fire R02, because 'गायब' is not in the",
          "  OPEN cue list, so the band is decided by other rules:", *tried(REJECTED_LIFE_SAFETY),
          "  This is a gap in the rule lexicon (docs/DECISIONS.md, Found but not changed).",
          "* Exact-text repeats were not used for item 8: paraphrases show that matching is not literal."]
    out = config.ROOT / "docs" / "DEMO_SCRIPT.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
