"""Run every demo input through the real pipeline (via the same service code as the web app,
on a fresh in-memory database) and write docs/DEMO_SCRIPT.md with the actual outputs.

    python scripts/run_demo_script.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from nagarvani import config, data, service  # noqa: E402
from nagarvani.console import safe_console  # noqa: E402
from nagarvani.examples import EXAMPLES  # noqa: E402
from nagarvani.store import Store  # noqa: E402

SAY = {
    "clean_marathi": "A clear complaint, a known place, high confidence: it goes straight to the department. R21 (no water) makes it P2.",
    "romanised": "Romanised Marathi works because the classifier uses character n-grams and the gazetteer has Latin aliases.",
    "code_mixed": "Marathi and English mixed in one sentence, as people actually speak.",
    "life_safety": "The rule base, not the model, decides life safety. R01 fires on the cue words shown, and the band is forced to P1. The rule ID is on screen.",
    "fuzzy": "हडप्सर is not in the gazetteer, but it is within the similarity threshold of हडपसर, so the fuzzy fallback resolves it and the trace shows the score.",
    "unknown_place": "Undri is not in our gazetteer. The system does not guess a ward, so the gate sends it to a person. The citizen can also pick a ward in the optional dropdown.",
    "low_confidence": "Building materials on the road could be Building or Encroachment. The model's top probability is under 0.50, so it defers instead of guessing.",
    "failure": "An honest failure: the word for water dominates, and the classifier says Water Supply although this is a mosquito-breeding (Health) complaint. Its confidence is high and the place is known, so the gate does NOT catch it. The officer would correct it, and the correction is logged.",
}


REJECTED_LOW_CONFIDENCE = ["कोथरूडमध्ये खूप त्रास होतोय, कोणीतरी लक्ष द्या", "सहकारनगरमध्ये परिस्थिती खूप वाईट आहे"]


def row(store, tid):
    t = store.get(tid)
    tr = json.loads(t["trace_json"])
    rules = ", ".join(f"{f['rule']} ({f['action']})" for f in tr["severity"]["fired"])
    top3 = ", ".join(f"{d} {p:.2f}" for d, p in tr["top3"])
    w = tr["ward"]
    ward = f"{w['ward']} ({data.ward_names()[w['ward']]['en']}) via {w['method']}" if w["ward"] else f"not resolved ({w['reason']})"
    if w["method"] == "fuzzy":
        ward += f", matched '{w['matched_text']}' ≈ '{w['matched_alias']}' score {w['score']}"
    d = tr["duplicate"]
    dup = d["decision"] + (f", score {d['score']:.2f} vs #{d['ticket_id']}" if d["score"] is not None else "")
    return [f"* Ticket #{tid}: **{tr['gate']['decision']}**, status `{t['status']}`",
            f"* Department top 3: {top3}",
            f"* Ward: {ward}",
            f"* Severity: **{tr['severity']['band']}**; rules fired: {rules}",
            f"* Duplicate check: {dup}",
            f"* Gate reason: {tr['gate']['reason']}"]


def main():
    safe_console()
    store = Store(":memory:")
    ex = {e["key"]: e for e in EXAMPLES}
    L = ["# Demo script", "",
         "Generated by `python scripts/run_demo_script.py`. Each input below was run through the real",
         "pipeline (the same `service.submit` → `triage()` code the web app uses, on a fresh database), and",
         "the output shown is what it produced. Run `python scripts/reset_demo.py` before the demo: the",
         "seeded tickets do not touch these inputs' duplicate blocks, but re-check item 8 after any seed change.",
         "Every input is also a one-click example on the intake page (the fallback if the microphone fails).", "",
         f"Classifier artefact: C = {json.loads(config.CLASSIFIER_PATH.with_suffix('.json').read_text(encoding='utf-8'))['C']}.", ""]
    n = 0
    for key in ["clean_marathi", "romanised", "code_mixed", "life_safety", "fuzzy", "unknown_place", "low_confidence"]:
        n += 1
        e = ex[key]
        tid, _ = service.submit(store, text=e["text"], channel="typed")
        L += [f"## {n}. {e['behaviour']}", "", f"Input: `{e['text']}`", ""] + row(store, tid) + ["", f"Say: {SAY[key]}", ""]
    n += 1
    L += [f"## {n}. Triple duplicate with escalation", "",
          "Submit the three reports one after another (three different wordings of the same pothole).", ""]
    ids = []
    for key in ["dup1", "dup2", "dup3"]:
        e = ex[key]
        tid, _ = service.submit(store, text=e["text"], channel="typed")
        ids.append(tid)
        L += [f"### {e['behaviour']}", "", f"Input: `{e['text']}`", ""] + row(store, tid) + [""]
    p = store.get(ids[0])
    L += [f"Result on the first ticket #{ids[0]}: {p['report_count']} reports, priority **{p['priority']}**, "
          f"escalation note: \"{p['escalation']}\".", "",
          "Say: the reports are merged, not duplicated in the queue. At the third report R32 fires and the open ticket "
          "moves up one band. Show the first report's ticket in the officer queue: it is marked '3 reports' and 'escalated'.", ""]
    n += 1
    e = ex["failure"]
    tid, _ = service.submit(store, text=e["text"], channel="typed")
    test = {r["id"]: r for r in data.load_test()}["T088"]
    L += [f"## {n}. {e['behaviour']}", "", f"Input: `{e['text']}` (test item T088; gold label {test['department']})", ""]
    L += row(store, tid) + ["", f"Say: {SAY['failure']}", ""]
    L += ["## Spoken versions", "",
          "Read any of the inputs aloud with the Marathi toggle on. The transcript appears for checking before submission.",
          "Whisper's transcript will differ from the typed text, so the outcome may differ. That is real, and it is",
          "why the citizen checks the transcript. If the microphone fails, use the example buttons.",
          "A WhatsApp voice note (.ogg) can be uploaded with the file button.", ""]
    from nagarvani.pipeline import triage
    tried = []
    for t in REJECTED_LOW_CONFIDENCE:
        r = triage(t)
        tried.append(f"  * `{t}` → {r.department} {r.confidence:.2f}, {r.gate.decision}")
    L += ["## Inputs that were tried and rejected", "",
          "* These were candidates for item 7 (low confidence → review). Re-run just now, they give:", *tried,
          "  Vague complaints are confidently sent to Health and auto-routed. This is a real weakness",
          "  (see docs/HANDOVER.md), and it is why item 7 uses a complaint that is genuinely between two departments.",
          "* Exact-text repeats were not used for item 8: paraphrases show that matching is not literal."]
    out = config.ROOT / "docs" / "DEMO_SCRIPT.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
